//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerNode.ComputeNodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComputeNodeService.IComputeNode")]
    public interface IComputeNode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeNode/IsWorking", ReplyAction="http://tempuri.org/IComputeNode/IsWorkingResponse")]
        bool IsWorking();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IComputeNode/IsWorking", ReplyAction="http://tempuri.org/IComputeNode/IsWorkingResponse")]
        System.IAsyncResult BeginIsWorking(System.AsyncCallback callback, object asyncState);
        
        bool EndIsWorking(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeNode/RestorePassword", ReplyAction="http://tempuri.org/IComputeNode/RestorePasswordResponse")]
        ComputeNodeServiceLib.RestorePasswordResult RestorePassword(string passwordHash, char[] startSymbolsRange);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IComputeNode/RestorePassword", ReplyAction="http://tempuri.org/IComputeNode/RestorePasswordResponse")]
        System.IAsyncResult BeginRestorePassword(string passwordHash, char[] startSymbolsRange, System.AsyncCallback callback, object asyncState);
        
        ComputeNodeServiceLib.RestorePasswordResult EndRestorePassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeNode/GetComputeInformation", ReplyAction="http://tempuri.org/IComputeNode/GetComputeInformationResponse")]
        ComputeNodeServiceLib.RestorePasswordResult GetComputeInformation();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IComputeNode/GetComputeInformation", ReplyAction="http://tempuri.org/IComputeNode/GetComputeInformationResponse")]
        System.IAsyncResult BeginGetComputeInformation(System.AsyncCallback callback, object asyncState);
        
        ComputeNodeServiceLib.RestorePasswordResult EndGetComputeInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeNode/StopPasswordComputing", ReplyAction="http://tempuri.org/IComputeNode/StopPasswordComputingResponse")]
        bool StopPasswordComputing();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IComputeNode/StopPasswordComputing", ReplyAction="http://tempuri.org/IComputeNode/StopPasswordComputingResponse")]
        System.IAsyncResult BeginStopPasswordComputing(System.AsyncCallback callback, object asyncState);
        
        bool EndStopPasswordComputing(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComputeNodeChannel : ControllerNode.ComputeNodeService.IComputeNode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsWorkingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsWorkingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestorePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RestorePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComputeNodeServiceLib.RestorePasswordResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComputeNodeServiceLib.RestorePasswordResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetComputeInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetComputeInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComputeNodeServiceLib.RestorePasswordResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComputeNodeServiceLib.RestorePasswordResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StopPasswordComputingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StopPasswordComputingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComputeNodeClient : System.ServiceModel.ClientBase<ControllerNode.ComputeNodeService.IComputeNode>, ControllerNode.ComputeNodeService.IComputeNode {
        
        private BeginOperationDelegate onBeginIsWorkingDelegate;
        
        private EndOperationDelegate onEndIsWorkingDelegate;
        
        private System.Threading.SendOrPostCallback onIsWorkingCompletedDelegate;
        
        private BeginOperationDelegate onBeginRestorePasswordDelegate;
        
        private EndOperationDelegate onEndRestorePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onRestorePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetComputeInformationDelegate;
        
        private EndOperationDelegate onEndGetComputeInformationDelegate;
        
        private System.Threading.SendOrPostCallback onGetComputeInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginStopPasswordComputingDelegate;
        
        private EndOperationDelegate onEndStopPasswordComputingDelegate;
        
        private System.Threading.SendOrPostCallback onStopPasswordComputingCompletedDelegate;
        
        public ComputeNodeClient() {
        }
        
        public ComputeNodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComputeNodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputeNodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputeNodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<IsWorkingCompletedEventArgs> IsWorkingCompleted;
        
        public event System.EventHandler<RestorePasswordCompletedEventArgs> RestorePasswordCompleted;
        
        public event System.EventHandler<GetComputeInformationCompletedEventArgs> GetComputeInformationCompleted;
        
        public event System.EventHandler<StopPasswordComputingCompletedEventArgs> StopPasswordComputingCompleted;
        
        public bool IsWorking() {
            return base.Channel.IsWorking();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginIsWorking(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsWorking(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndIsWorking(System.IAsyncResult result) {
            return base.Channel.EndIsWorking(result);
        }
        
        private System.IAsyncResult OnBeginIsWorking(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginIsWorking(callback, asyncState);
        }
        
        private object[] OnEndIsWorking(System.IAsyncResult result) {
            bool retVal = this.EndIsWorking(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsWorkingCompleted(object state) {
            if ((this.IsWorkingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsWorkingCompleted(this, new IsWorkingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsWorkingAsync() {
            this.IsWorkingAsync(null);
        }
        
        public void IsWorkingAsync(object userState) {
            if ((this.onBeginIsWorkingDelegate == null)) {
                this.onBeginIsWorkingDelegate = new BeginOperationDelegate(this.OnBeginIsWorking);
            }
            if ((this.onEndIsWorkingDelegate == null)) {
                this.onEndIsWorkingDelegate = new EndOperationDelegate(this.OnEndIsWorking);
            }
            if ((this.onIsWorkingCompletedDelegate == null)) {
                this.onIsWorkingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsWorkingCompleted);
            }
            base.InvokeAsync(this.onBeginIsWorkingDelegate, null, this.onEndIsWorkingDelegate, this.onIsWorkingCompletedDelegate, userState);
        }
        
        public ComputeNodeServiceLib.RestorePasswordResult RestorePassword(string passwordHash, char[] startSymbolsRange) {
            return base.Channel.RestorePassword(passwordHash, startSymbolsRange);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRestorePassword(string passwordHash, char[] startSymbolsRange, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRestorePassword(passwordHash, startSymbolsRange, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComputeNodeServiceLib.RestorePasswordResult EndRestorePassword(System.IAsyncResult result) {
            return base.Channel.EndRestorePassword(result);
        }
        
        private System.IAsyncResult OnBeginRestorePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string passwordHash = ((string)(inValues[0]));
            char[] startSymbolsRange = ((char[])(inValues[1]));
            return this.BeginRestorePassword(passwordHash, startSymbolsRange, callback, asyncState);
        }
        
        private object[] OnEndRestorePassword(System.IAsyncResult result) {
            ComputeNodeServiceLib.RestorePasswordResult retVal = this.EndRestorePassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRestorePasswordCompleted(object state) {
            if ((this.RestorePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RestorePasswordCompleted(this, new RestorePasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RestorePasswordAsync(string passwordHash, char[] startSymbolsRange) {
            this.RestorePasswordAsync(passwordHash, startSymbolsRange, null);
        }
        
        public void RestorePasswordAsync(string passwordHash, char[] startSymbolsRange, object userState) {
            if ((this.onBeginRestorePasswordDelegate == null)) {
                this.onBeginRestorePasswordDelegate = new BeginOperationDelegate(this.OnBeginRestorePassword);
            }
            if ((this.onEndRestorePasswordDelegate == null)) {
                this.onEndRestorePasswordDelegate = new EndOperationDelegate(this.OnEndRestorePassword);
            }
            if ((this.onRestorePasswordCompletedDelegate == null)) {
                this.onRestorePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRestorePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginRestorePasswordDelegate, new object[] {
                        passwordHash,
                        startSymbolsRange}, this.onEndRestorePasswordDelegate, this.onRestorePasswordCompletedDelegate, userState);
        }
        
        public ComputeNodeServiceLib.RestorePasswordResult GetComputeInformation() {
            return base.Channel.GetComputeInformation();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetComputeInformation(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetComputeInformation(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComputeNodeServiceLib.RestorePasswordResult EndGetComputeInformation(System.IAsyncResult result) {
            return base.Channel.EndGetComputeInformation(result);
        }
        
        private System.IAsyncResult OnBeginGetComputeInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetComputeInformation(callback, asyncState);
        }
        
        private object[] OnEndGetComputeInformation(System.IAsyncResult result) {
            ComputeNodeServiceLib.RestorePasswordResult retVal = this.EndGetComputeInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetComputeInformationCompleted(object state) {
            if ((this.GetComputeInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetComputeInformationCompleted(this, new GetComputeInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetComputeInformationAsync() {
            this.GetComputeInformationAsync(null);
        }
        
        public void GetComputeInformationAsync(object userState) {
            if ((this.onBeginGetComputeInformationDelegate == null)) {
                this.onBeginGetComputeInformationDelegate = new BeginOperationDelegate(this.OnBeginGetComputeInformation);
            }
            if ((this.onEndGetComputeInformationDelegate == null)) {
                this.onEndGetComputeInformationDelegate = new EndOperationDelegate(this.OnEndGetComputeInformation);
            }
            if ((this.onGetComputeInformationCompletedDelegate == null)) {
                this.onGetComputeInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetComputeInformationCompleted);
            }
            base.InvokeAsync(this.onBeginGetComputeInformationDelegate, null, this.onEndGetComputeInformationDelegate, this.onGetComputeInformationCompletedDelegate, userState);
        }
        
        public bool StopPasswordComputing() {
            return base.Channel.StopPasswordComputing();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStopPasswordComputing(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStopPasswordComputing(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndStopPasswordComputing(System.IAsyncResult result) {
            return base.Channel.EndStopPasswordComputing(result);
        }
        
        private System.IAsyncResult OnBeginStopPasswordComputing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginStopPasswordComputing(callback, asyncState);
        }
        
        private object[] OnEndStopPasswordComputing(System.IAsyncResult result) {
            bool retVal = this.EndStopPasswordComputing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStopPasswordComputingCompleted(object state) {
            if ((this.StopPasswordComputingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StopPasswordComputingCompleted(this, new StopPasswordComputingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StopPasswordComputingAsync() {
            this.StopPasswordComputingAsync(null);
        }
        
        public void StopPasswordComputingAsync(object userState) {
            if ((this.onBeginStopPasswordComputingDelegate == null)) {
                this.onBeginStopPasswordComputingDelegate = new BeginOperationDelegate(this.OnBeginStopPasswordComputing);
            }
            if ((this.onEndStopPasswordComputingDelegate == null)) {
                this.onEndStopPasswordComputingDelegate = new EndOperationDelegate(this.OnEndStopPasswordComputing);
            }
            if ((this.onStopPasswordComputingCompletedDelegate == null)) {
                this.onStopPasswordComputingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStopPasswordComputingCompleted);
            }
            base.InvokeAsync(this.onBeginStopPasswordComputingDelegate, null, this.onEndStopPasswordComputingDelegate, this.onStopPasswordComputingCompletedDelegate, userState);
        }
    }
}
